use_frameworks!

platform :ios, '9.0'

target 'HQSDK_Example' do
  pod 'HQSDK', :path => '../'

  target 'HQSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
    pod 'AFNetworking'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'ReactiveObjC'
    pod 'SDWebImage'
    pod 'LSTPopView'
    pod 'TZImagePickerController'
  end
end
